//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_and_Tourism.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tourismEntities : DbContext
    {
        public tourismEntities()
            : base("name=tourismEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<TBL_Booking> TBL_Booking { get; set; }
        public virtual DbSet<TBL_feedback> TBL_feedback { get; set; }
        public virtual DbSet<TBL_Login> TBL_Login { get; set; }
        public virtual DbSet<TBL_registration> TBL_registration { get; set; }
    }
}
