//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_and_Tourism.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Booking
    {
        public int id { get; set; }
        public string travel { get; set; }
        public string destination { get; set; }
        public string checkin { get; set; }
        public string person { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string msg { get; set; }
    }
}
